ApiConfig:
  Url: 127.0.0.1:13579

MqttConfig:
  Url: tcp://127.0.0.1:1883
  Name: Ravigation

RedisConfig:
  MaxIdle: 2
  MaxActive: 5
  MaxIdleTimeout: 60
  Host: 127.0.0.1:6379
  Password:
  Db: 0
  ConnectTimeout: 10
  ReadTimeout: 10
  WriteTimeout: 10

AgvGroup:
  - {name: agv1,ip: 127.0.0.1}
  - {name: agv2,ip: 127.0.0.1}

