package agvManager

const (
	TOPIC_AGV_CONNECT = "/connect"
	TOPIC_AGV_STATE = "/state"
	TOPIC_AGV_COMMAND = "/command"
	TOPIC_AGV_FINISH = "/finish"
)


const (
	TOPIC_RAVI_AGV_PREFIX = "agv"
	TOPIC_RAVI_AGV_CONNECT = TOPIC_RAVI_AGV_PREFIX + TOPIC_AGV_CONNECT
	TOPIC_RAVI_AGV_STATE = TOPIC_RAVI_AGV_PREFIX + TOPIC_AGV_STATE
	TOPIC_RAVI_AGV_COMMAND = TOPIC_RAVI_AGV_PREFIX + TOPIC_AGV_COMMAND
	TOPIC_RAVI_AGV_FINISH = TOPIC_RAVI_AGV_PREFIX + TOPIC_AGV_FINISH
)
